### ISSUE TITLE
Adding more BLE sensors?

### ISSUE THREAD

**Issue by lennycb** [victronenergy/dbus-ble-sensors#1]
for example: LYWSDCGQ
![51xPG6gd+uL _AC_SY355_](https://user-images.githubusercontent.com/23618370/145584460-50466321-dab8-4fe4-92f0-2aead96c68df.jpg)

Maybe it will help with the integration. (I hope I can insert the link here. If you don't want it, please delete it.)

https://home-is-where-you-hang-your-hack.github.io/ble_monitor/MiBeacon_protocol#reverse-engineering-the-mibeacon-protocol

**Comment by mpvader** [comment]
Adding more temp/humidity sensors could be done ofcourse, its software. But not something we’re currently interested in.

You, or anyone else, is welcome to extend this software him/herself, and send us a Pull Request.

And, depending on what its for and its quality we’ll take a look.

Note that we don’t need to do anything to let you use a modified version of the software. You can change it, and self install it on your gx device.

for help or further discussion, best use community. Not an issue.

all the best, Matthijs
