### ISSUE TITLE
Support Mopeka Pro Check Universal Sensor

### ISSUE THREAD

**Issue by rustyfreeman** [victronenergy/dbus-ble-sensors#4]
Mopeka have release a newer Pro Check Universal Sensor which has many benefits over the existing sensor. Currently this sensor is unrecognised by venus os.

**Comment by mpvader** [comment]
Hi, its being worked on - although a bit slowly. Current status is we're awaiting samples to test against.

**Comment by mpvader** [comment]
there is an issue in our internal repo, venus-private, to track this.

**Comment by robsweet** [comment]
@rustyfreeman In addition to the new Universal sensors, the updated code also supports their top-down sensors.  :)

**Comment by mansr** [comment]
Support has been added in v0.13.
